⬆️: Upgrade to React 18
Fintan-contents/example-chat pull request #2
Opened 2023-11-07 02:54 UTC by sinho-lee

## ✅ What's done

- [x] Reactのバージョンアップ v17.0.3 → v18.2.0
- [x] react-router-domのバージョンアップ v5.2.0 → v5.3.4
  - v5.3.4に上げた理由はv5.3.3からはReact v18との互換性の問題を解決したので、v5.3系の最新バージョンにしました。詳細についてはOtherのreact-router-domのURL先に記載されています。
- [x] Reactのバージョンアップによるソースコード修正
- [x] react-router-domのバージョンアップによるソースコード修正

## Tests

- [x] 各画面が表示されることを打鍵テストで確認
- [x] 各機能が問題なく動くことを打鍵テストで確認

## Other (messages to reviewers, concerns, etc.)

- ReactのバージョンアップによるReactのエラーを解消するため、参考にした内容は下記の通りです。
  -  [クライアントレンダリング API への変更](https://ja.react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis)
   - [TypeScript 型定義の変更](https://ja.react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-typescript-definitions)
- react-router-domのバージョンアップによるreact-router-domのエラーを解消するため、参考にした内容は下記の通りです。
   - [Fix: make v5 Router compatible with v18 StrictMode](https://github.com/remix-run/react-router/pull/8831)
   - [BrowserRouterの問題](https://github.com/remix-run/react-router/issues/7870#issuecomment-1099884642)

2023-11-10 07:04 UTC, creature-water-valley requested changes

2023-11-10 07:04 UTC, creature-water-valley commented on frontend/package.json
>      "@zxing/library": "^0.18.4",
アップグレードしているライブラリとしていないライブラリは、どういう基準ですかね？
チーム内で話し合っていなければ、方針を決めた方が良さそうです。

（「メジャーは上げなくても、LockfileMaintenanceはしておく」など）

2023-11-10 07:04 UTC, creature-water-valley commented on frontend/src/index.tsx
このファイルに関する指摘ではないのですが、差分がないのでここに記載します。

`npm run lint`を実行すると、警告/エラーが結構あるようです。

2023-11-10 07:04 UTC, creature-water-valley commented on frontend/src/framework/logging/Logger.dev.ts
> +export function debug(message?: any, ...optionalParams: any[]): void {
`export`しているのはなぜでしょう？

2023-11-10 07:04 UTC, creature-water-valley commented on frontend/src/framework/logging/Logger.prod.ts
> +export function debug(message?: any, ...optionalParams: any[]): void {
`export`しているのはなぜでしょう？

2023-11-10 07:04 UTC, creature-water-valley commented on frontend/src/chat/components/Routing.tsx
> +import { Redirect, Route, Switch } from 'react-router-dom';
このページのコメントに記載されているReact Routerに関するリンクページがNot Foundになっているようです。

- https://reacttraining.com/react-router/web/guides/quick-start
- https://reacttraining.com/react-router/web/api/Route

2023-11-10 07:04 UTC, creature-water-valley commented on frontend/package.json
>      "@zxing/library": "^0.18.4",
今回のアップグレードとは関係ないのですが、`@zxing/library`の`BrowserQRCodeSvgWriter`はdeprecatedになっているので、修正した方が良いかもしれません。
https://github.com/Fintan-contents/example-chat/blob/master/frontend/src/chat/components/basics/QRCode.tsx#L14

（チーム内に共有した対応方針決めましょう。）

2023-11-10 07:49 UTC, creature-water-valley commented on frontend/src/index.tsx
このファイルに関する指摘ではないのですが、記載する所がないのでここに記載します。

チャットにコメントを入力すると以下の警告がコンソールに出ますが、これは元々ですかね？（そもそもそちらの環境でも発生します？）

```
Warning: Encountered two children with the same key, `17`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

2023-11-10 07:57 UTC, creature-water-valley commented on frontend/src/index.tsx
以下の手順で発生する模様

- チャットでコメント送信
- `http://localhost:3000`を直接リンクに入れてTOPページを開く
- ログイン
- チャットでコメント送信

2023-11-14 07:56 UTC, sinho-lee commented on frontend/package.json
>      "@zxing/library": "^0.18.4",
Reactに関するライブラリ(`react`、`react-dom`)はReactバージョンアップチケットの内容だったので対応してます。
Reactのバージョンアップによる不具合のため、`react-router-dom`はバージョンアップしました。
また、`node`、`react-script`、`typescript`は朝会で話があったので、バージョンアップしました。

2023-11-14 07:57 UTC, sinho-lee commented on frontend/src/framework/logging/Logger.dev.ts
> +export function debug(message?: any, ...optionalParams: any[]): void {
削除漏れでしたので、対応しました。
対応Commit: 0b36047eda17ad347e32a5a858e57cbdf29abbd6

2023-11-14 07:57 UTC, sinho-lee commented on frontend/src/framework/logging/Logger.prod.ts
> +export function debug(message?: any, ...optionalParams: any[]): void {
削除漏れでしたので、対応しました。
対応Commit: 0b36047eda17ad347e32a5a858e57cbdf29abbd6

2023-11-14 07:58 UTC, sinho-lee commented on frontend/src/chat/components/Routing.tsx
> +import { Redirect, Route, Switch } from 'react-router-dom';
リンク修正しました。
対応Commit: b6fccabc3c69c9ad9d448a780919868ca9d3b4b6

2023-11-15 01:00 UTC, sinho-lee commented on frontend/package.json
>      "@zxing/library": "^0.18.4",
朝会で`@zxing/browser`を使用することになってので、別PRで対応します。

2023-11-15 01:17 UTC, sinho-lee commented on frontend/src/index.tsx
masterブランチで確認してみましたが、警告がコンソールに出てないです。
バージョンアップ後、上記の現象が起こっていますので、調べてみます。

2023-11-15 02:25 UTC, creature-water-valley commented on frontend/package.json
>      "@zxing/library": "^0.18.4",
チーム内で話して、以下方針としました。

- `@fortawesome`は、vupによる影響が大きかもなのでこのPRでは対応しない。
- `moment`は既に公式が利用を推奨していないが、対応するのは大変なので、このPRでは対応しない。

2023-11-15 02:29 UTC, creature-water-valley commented on frontend/package.json
差分がないので、ここに記載します。
Node.jsのvupもお願いします。

2023-11-15 07:20 UTC, sinho-lee commented on frontend/src/index.tsx
このPRで警告/エラーを解消した方が良いでしょうか。

2023-11-15 08:28 UTC, in-a-paddy commented on frontend/package.json
`@types/node`のバージョンもあわせておいた方が良いね。

2023-11-15 08:32 UTC, in-a-paddy commented on frontend/src/index.tsx
vupに起因するものは、このPRで解消しておきたいですね。

2023-11-15 08:35 UTC, sinho-lee commented on frontend/src/index.tsx
lintに関してはvup前から警告/エラーが出たので、別PRで対応した方が良いでしょうか。

2023-11-15 08:49 UTC, sinho-lee commented on frontend/package.json
> `@types/node`のバージョンもあわせておいた方が良いね。

対応Commit: 01dba9f3e0d92abef3868e0fb13bf96dbaafef40

2023-11-16 00:12 UTC, creature-water-valley commented on frontend/src/index.tsx
`master`ブランチで`npm run lint`を実行してみましたが、警告やエラーは出てないようです。
なので、vupによる影響かなぁと思います。

2023-11-16 00:14 UTC, creature-water-valley commented on frontend/package.json
READMEの修正も必要そうです。
https://github.com/Fintan-contents/example-chat/blob/master/README.md?plain=1#L35

2023-11-16 00:20 UTC, sinho-lee commented on frontend/package.json
> READMEの修正も必要そうです。
https://github.com/Fintan-contents/example-chat/blob/master/README.md?plain=1#L35

修正しました。
対応Commit: c3ea361363c63fb09e2de2479a496a63f526bdef

gitlab-ci.ymlのimageも修正した方が良いでしょうか。

2023-11-16 00:23 UTC, creature-water-valley commented on frontend/package.json
そちらも修正した方が良さそうですが、試す環境ってどこかにあるんですかね？（確認してみましょう。）

2023-11-16 06:41 UTC, creature-water-valley commented on frontend/package.json
gitlab-ciは現状では環境なくて、後々Github Actionsに移行する予定とのこと。
そのため、`gitlab-ci.yml`の修正は不要となりました。

2023-11-16 07:59 UTC, in-a-paddy commented on frontend/src/chat/components/basics/QRCode.tsx
> +      }
❓  全体的にオプショナルチェーンはなくても大丈夫そうな気がしますが、エラーになりますかね？（個人的にはL13のnullチェックも `ref.current != null` の方が好みですが、まぁ型としては `undefined` は含まれないのでそのままでもいいかな、と）

```suggestion
      const svg = codeWriter.write(input, width, height);
      if (ref.current.firstChild) {
        ref.current.replaceChild(svg, ref.current.firstChild);
      } else {
        ref.current.appendChild(svg);
      }
```

2023-11-16 08:06 UTC, sinho-lee commented on frontend/src/chat/components/basics/QRCode.tsx
> +      }
オプショナルチェーンがなくてもエラーにならないです。上記のように修正します。

2023-11-17 02:25 UTC, sinho-lee commented on frontend/src/index.tsx
対応Commit
  - `@testing-library/react`のバージョンアップ: 46f39825977c521257988b8f0d03b18ec10e8a89
  -  Lintエラー解消とテストコード修正: 20d218c8b4db0f52ee49e143f1416795c0ec0e9b, fc173239373f8610ffb6415a349852d4a441cef9

2023-11-17 02:26 UTC, sinho-lee commented on frontend/src/index.tsx
対応Commit: f9f83b90f57ae7fe7b76a88015d3cb0430f5a670, 5d3076d00053aedf22c4f253684e7ea1f33f6331

2023-11-17 07:06 UTC, in-a-paddy commented on frontend/src/framework/backend/NotificationService.ts
⚠ Lintエラーが残ってますね。

```console
121:1  warning  Assign instance to a variable before exporting as module default  import/no-anonymous-default-export
```

2023-11-17 07:07 UTC, creature-water-valley commented on frontend/src/framework/backend/RestClient.test.ts
> +    let errorResponse: any;
async/awaitを使うなら、↓のように記載した方がシンプルで良さそうに思います。

```ts
await expect(promise).rejects.toEqual({status: 501});
```

2023-11-17 07:16 UTC, creature-water-valley commented on frontend/package.json
> +    "@testing-library/react": "^14.1.0",
ここのvupって、`spa-restapi-handson`にも必要ですよね。

2023-11-17 07:17 UTC, creature-water-valley commented on frontend/src/framework/validation/Validation.test.tsx
このファイルの修正も、`spa-restapi-handson`に反映しないとですかね。

2023-11-17 08:09 UTC, sinho-lee commented on frontend/src/framework/backend/RestClient.test.ts
> +    let errorResponse: any;
ありがとうございます。上記の内容で対応しました。
対応Commit: 644c2cb6a9bb90a129f6af53f571eea261b5dbf9

2023-11-17 08:10 UTC, sinho-lee commented on frontend/src/framework/backend/NotificationService.ts
失礼いたしました。ソースコード修正し、警告も解消しました。
対応Commit: 25b620d11ebc1bd4b3f366ac6deb1f0b285296b2

2023-11-17 08:12 UTC, sinho-lee commented on frontend/package.json
> +    "@testing-library/react": "^14.1.0",
`spa-restapi-handson`にバージョンアップと[テストコード](https://github.com/Fintan-contents/example-chat/pull/2#discussion_r1396790524)も含めて対応します。

2023-11-17 08:35 UTC, creature-water-valley commented on frontend/src/framework/validation/Validation.test.tsx
↓と同様
- https://github.com/Fintan-contents/example-chat/pull/2#discussion_r1396843677

2023-11-17 08:53 UTC, creature-water-valley approved these changes

2023-11-17 09:06 UTC, in-a-paddy approved these changes

2023-11-17 09:07 UTC, merged